# Generated by Django 4.0.6 on 2022-08-23 07:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=200)),
                ('file_field', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['torrent'])])),
                ('date', models.DateField(auto_now_add=True)),
                ('file_size', models.CharField(default=0, max_length=20)),
                ('magnet', models.CharField(default='', max_length=200)),
                ('infohash', models.CharField(default=0, max_length=200)),
                ('total_peers', models.IntegerField(default=0)),
                ('total_seeds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
