# Generated by Django 4.0.6 on 2022-08-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torfile',
            old_name='total_peers',
            new_name='total_completed',
        ),
    ]
