# Generated by Django 4.1 on 2022-08-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_total_peers_torfile_total_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='torfile',
            name='category',
            field=models.CharField(choices=[('Documents', 'DOCS'), ('Video', 'VIDS'), ('Research', 'RSRCH'), ('Software', 'SFTWR')], default='None', max_length=10),
        ),
    ]
