# Generated by Django 4.1 on 2022-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_torfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torfile',
            name='category',
            field=models.CharField(choices=[('Documents', 'Documents'), ('Videos', 'Video'), ('Research', 'Research'), ('Software', 'Software'), ('Other', 'Other')], default='None', max_length=10),
        ),
    ]
