# Generated by Django 4.1 on 2022-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_torfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torfile',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
