# Generated by Django 4.1 on 2022-08-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_torfile_leechers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torfile',
            old_name='leechers',
            new_name='total_leechers',
        ),
    ]
