# Generated by Django 4.1.1 on 2022-10-14 08:18

from django.db import migrations, models
import main.validator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_leechers_torfile_total_leechers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torfile',
            name='file_field',
            field=models.FileField(upload_to='uploads/', validators=[main.validator.validate_is_torrent]),
        ),
    ]
